[workspace]
members = ["crates/*"]
exclude = ["packages/playground/src-tauri"]
resolver = "2"

[workspace.package]
homepage = "https://github.com/manatsujs/manatsu"
repository = "https://github.com/manatsujs/manatsu"
authors = ["Andrew Ferreira <andrew.shien2@gmail.com>"]
license = "MIT"
edition = "2021"
readme = "README.md"
categories = ["gui", "web-programming"]