[package]
name = "manatsu"
version = "0.1.35"
description = "CLI tools for Manatsu"
homepage = "https://github.com/manatsujs/manatsu"
repository = "https://github.com/manatsujs/manatsu"
authors = ["Andrew Ferreira <andrew.shien2@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
convert_case = "0.6"
