[package]
name = "playground"
version = "0.5.2"
description = "Manatsu playground"
homepage = "https://github.com/tsukilabs/manatsu"
repository = "https://github.com/tsukilabs/manatsu"
authors = ["Andrew Ferreira <andrew.shien2@gmail.com>"]
license = "MIT"
edition = "2021"
rust-version = "1.76"
publish = false

[build-dependencies.tauri-build]
version = "1.5.1"
features = []

[dependencies]
anyhow = "1.0.81"
chrono = "0.4.35"
serde_json = "1.0.114"
tauri-plugin-window-state = "0.1.0"
thiserror = "1.0.58"

[dependencies.tauri]
version = "1.6.1"
features = []

[dependencies.serde]
version = "1.0.197"
features = ["derive"]

[dependencies.tokio]
version = "1.36.0"
features = ["macros", "rt-multi-thread"]

[dependencies.tauri-plugin-manatsu]
version = "0.5"
path = "../../../crates/tauri-plugin-manatsu"

[features]
custom-protocol = ["tauri/custom-protocol"]
