[package]
name = "playground"
version = "0.2.22"
description = "Manatsu playground"
homepage = "https://github.com/manatsujs/manatsu"
repository = "https://github.com/manatsujs/manatsu"
authors = ["Andrew Ferreira <andrew.shien2@gmail.com>"]
license = "MIT"
edition = "2021"

[build-dependencies.tauri-build]
version = "1.5"
features = []

[dependencies]
chrono = "0.4"
serde_json = "1.0"
tauri-plugin-manatsu = "*"
tauri-plugin-window-state = "0.1"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.tauri]
version = "1.5"
features = []

[features]
custom-protocol = ["tauri/custom-protocol"]
