[package]
name = "playground"
version = "0.4.1"
description = "Manatsu playground"
homepage = "https://github.com/tsukilabs/manatsu"
repository = "https://github.com/tsukilabs/manatsu"
authors = ["Andrew Ferreira <andrew.shien2@gmail.com>"]
license = "MIT"
edition = "2021"
publish = false

[build-dependencies.tauri-build]
version = "2.0.0-beta.3"
features = []

[dependencies]
chrono = "0.4.34"
serde_json = "1.0.114"

[dependencies.tauri-plugin-window-state]
version = "2.0.0-beta.1"

[dependencies.tauri]
version = "2.0.0-beta.4"
features = []

[dependencies.serde]
version = "1.0.197"
features = ["derive"]

[dependencies.tauri-plugin-manatsu]
version = "0.4.0"
path = "../../../crates/tauri-plugin-manatsu"

[features]
custom-protocol = ["tauri/custom-protocol"]
