"$schema" = "schemas/schema.json"
[default]
description = "Default permissions for the Manatsu plugin"
permissions = [
  "allow-save-log",
  "allow-set-default-vue-version",
  "allow-version-snapshot",
]
