"$schema" = "schemas/schema.json"
[default]
description = "Default permissions for the Manatsu plugin"
permissions = [
  "allow-log-path",
  "allow-is-dev",
  "allow-manatsu-version",
  "allow-read-logs",
  "allow-save-log",
  "allow-version-snapshot",
]
