name: Test PR

on:
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm
      - run: cargo clippy --manifest-path=cli/Cargo.toml -- -D warnings
      - run: cargo test --manifest-path=cli/Cargo.toml
      - run: pnpm install
      - run: pnpm test
